### ISSUE TITLE
Getting empty responses via API

### ISSUE THREAD

**Issue by raulls0** [oobabooga/text-generation-webui#4921]
### Describe the bug

When I am using the API to get responses from the bot, if I already have a few messages, it often returns an empty response.

And from there he always gives me empty answers, and I have to start the conversation again.

What I'm doing is, when sending the message, I attach the entire conversation, so that bot doesn't lose the "memory" (like the simple memory extension).

So a temporary solution that I have found is to attach only the last 30 messages, so it no longer gives me empty responses.

Do you guys have any idea why this happens? What do I have to modify so that I can attach the entire conversation without it returning an empty response?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

sending some messages via api,then i will get empty response

### Screenshot

When it gives empty reply, i got this message:

Traceback (most recent call last):
  File "/app/modules/text_generation.py", line 387, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/app/modules/exllamav2.py", line 111, in generate_with_streaming
    self.model.forward(ids[:, :-1], self.cache, input_mask=None, preprocess_only=True, loras=self.loras)
  File "/venv/lib/python3.10/site-packages/exllamav2/model.py", line 358, in forward
    assert past_len + q_len <= cache.max_seq_len, "Total sequence length exceeds cache size in model.forward"
AssertionError: Total sequence length exceeds cache size in model.forward
Output generated in 0.01 seconds (0.00 tokens/s, 0 tokens, context 2333, seed 1125645435)

### Logs

```shell
none
```

### System Info

```shell
rtx 3090 24gb
```

**Comment by zencyon** [comment]
I have noticed similar things, didn't used to see empty responses much before new api, 
but its sometimes hard to tell if it's the model or something else

when you say attach the entire conversation, you mean you send along the history dictionary, right?

that's what i'm doing and it seems works fine for most part with most models, 
sometimes there are few empty replies, but it can recover from it

with Orca2 models specifically, i see them fail once their prompt window gets filled and they start replying with empty
another problem i saw Orca2 have was answering for the user
(that model was not really tuned for chat, so i assumed that was why)

it made me wonder if there was something changed related to the end-of-sentence EoS token or an extra return/nextline either from the model api response or the code that extracts the response 

it could just be the model tho, yet seems to work in Ooba's own chat

**Comment by zwilch** [comment]
I have something similary. On chat page it respond right but using the api I get "0" tokens very quickly.
For example 0 tokens in api with lmsys/vicuna-13b-v1.5-16k 
RTX 3060 12GB.

**Comment by raulls0** [comment]
> attach the entire conversation

Hi, thanks for your reply.

Yes, i attached the entire conversation, and i got empty reply. I made some modifications, but still getting empty reply -_-

**Comment by dragos240** [comment]
Getting a similar behavior on 781367b. I've tried exllama (1 & 2), exllama2_HF, and AutoGPTQ and I'm getting different errors (depending on loader):

exllama
```
Traceback (most recent call last):
  File "C:\Users\nat\Documents\Programs\text-generation-webui\modules\text_generation.py", line 405, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "C:\Users\nat\Documents\Programs\text-generation-webui\modules\exllama.py", line 160, in generate_with_streaming
    token = self.generator.gen_single_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nat\Documents\Programs\text-generation-webui\installer_files\env\Lib\site-packages\exllama\generator.py", line 353, in gen_single_token
    self.apply_rep_penalty(logits)
  File "C:\Users\nat\Documents\Programs\text-generation-webui\installer_files\env\Lib\site-packages\exllama\generator.py", line 335, in apply_rep_penalty
    cuda_ext.ext_apply_rep_penalty_mask_cpu(self.sequence,
  File "C:\Users\nat\Documents\Programs\text-generation-webui\installer_files\env\Lib\site-packages\exllama\cuda_ext.py", line 110, in ext_apply_rep_penalty_mask_cpu
    apply_rep_penalty(sequence, penalty_max, sustain, decay, logits)
TypeError: apply_rep_penalty(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: float, arg2: int, arg3: int, arg4: torch.Tensor) -> None

Invoked with: tensor([], size=(1, 0), dtype=torch.int64), 1, 1024, 128, None
Output generated in 0.00 seconds (0.00 tokens/s, 0 tokens, context 28, seed 1474322178)
```

exllama v2:
```
Traceback (most recent call last):
  File "C:\Users\nat\Documents\Programs\text-generation-webui\modules\text_generation.py", line 405, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "C:\Users\nat\Documents\Programs\text-generation-webui\modules\exllamav2.py", line 131, in generate_with_streaming
    logits = self.model.forward(ids[:, -1:], self.cache, input_mask=None, loras=self.loras).float().cpu()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'float'
Output generated in 0.00 seconds (0.00 tokens/s, 0 tokens, context 28, seed 276082822)
```

I was using 2d97897 before, which was working. I was using "smart connections" for obsidian, with a modified API call to match the ooba instance instead of openai. I'm not sure the exact calls it's making, but it was working before and broke when I updated to 781367b

**Comment by dragos240** [comment]
With the help of Wireshark, I was able to intercept the request and found the parameter causing the issue:
```
curl -L 'http://127.0.0.1:5000/v1/chat/completions' -H 'Content-Type: application/json' -d '{
    "model": "gpt-3.5-turbo-16k",
    "messages": [
        {
            "role": "user",
            "content": "Hello"
        }
    ],
    "max_tokens": 11977,
    "temperature": 0.3,
    "top_p": 1,
    "presence_penalty": 0,
    "frequency_penalty": 0,
    "stream": false,
    "stop": null,
    "n": 1
}'
```
The `max_tokens` parameter is causing the issue. Removing it makes the problem stop.

**Comment by raulls0** [comment]
> With the help of Wireshark, I was able to intercept the request and found the parameter causing the issue:
> 
> ```
> curl -L 'http://127.0.0.1:5000/v1/chat/completions' -H 'Content-Type: application/json' -d '{
>     "model": "gpt-3.5-turbo-16k",
>     "messages": [
>         {
>             "role": "user",
>             "content": "Hello"
>         }
>     ],
>     "max_tokens": 11977,
>     "temperature": 0.3,
>     "top_p": 1,
>     "presence_penalty": 0,
>     "frequency_penalty": 0,
>     "stream": false,
>     "stop": null,
>     "n": 1
> }'
> ```
> 
> The `max_tokens` parameter is causing the issue. Removing it makes the problem stop.

Hi, thanks for your reply.

I tried to remove "max_tokens" but after that still getting empty messages after a while.
