### ISSUE TITLE
Traceback when loading LoRA - ValueError: Target module QuantLinear() is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported.

### ISSUE THREAD

**Issue by GreenTeaBD** [oobabooga/text-generation-webui#2183]
### Describe the bug

This started in Windows 11. Originally I had llama-30b-4bit-128g (one from mid-march I think from a popular torrent.) The models work fine on their own, but then I tried to apply a LoRA to them. The first was this one [Aeala/VicUnlocked-alpaca-half-30b-LoRA](https://huggingface.co/Aeala/VicUnlocked-alpaca-half-30b-LoRA)

I try to apply that and, instead of applying it I get a traceback that ends with "ValueError: Target module QuantLinear() is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported."

Then further tries get me a traceback that ends with "AttributeError: 'LlamaForCausalLM' object has no attribute 'disable_adapter'"

So then I tried [kaiokendev/alpaca-lora-30b-4bit](https://huggingface.co/kaiokendev/alpaca-lora-30b-4bit) and, same thing.

Thinking it may be my base model, I grabbed llama-7b-4bit and [tloen/alpaca-lora-7b](https://huggingface.co/tloen/alpaca-lora-7b) but, same error.

So I ran update_windows.bat to hopefully reinstall whatever may be broken, I only tested a couple times but it was still giving me the "ValueError: Target module QuantLinear() is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported." error. I didn't see the other traceback, but I didnt try very many times before deciding to try the next thing.

So, I have a WSL2 Ubuntu install that's all set up for this stuff. I went and installed the Linux version there and surprisingly, same exact error.

The fact that I didn't already find an issue for this makes me suspect I'm doing something very wrong, but I dunno, I'm at a loss. Maybe it is a bug? Maybe the tracebacks can help someone see something that I cant see, or can thinking of something to try that I didn't think up?

Thanks

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I just installed the webui with the one click installer in each OS, copy over the models, copy over the LoRAs, load the model, try to apply the LoRA, crash

### Logs

```shell
INFO:Applying the following LoRAs to llama-30b-4bit-128g: kaiokendev_alpaca-lora-30b-4bit
Traceback (most recent call last):
  File "I:\ob\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\ob\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "I:\ob\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\ob\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\ob\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\ob\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\ob\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "I:\ob\text-generation-webui\server.py", line 76, in load_lora_wrapper
    add_lora_to_model(selected_loras)
  File "I:\ob\text-generation-webui\modules\LoRA.py", line 43, in add_lora_to_model
    shared.model = PeftModel.from_pretrained(shared.model, Path(f"{shared.args.lora_dir}/{lora_names[0]}"), **params)
  File "I:\ob\installer_files\env\lib\site-packages\peft\peft_model.py", line 180, in from_pretrained
    model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name)
  File "I:\ob\installer_files\env\lib\site-packages\peft\peft_model.py", line 670, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "I:\ob\installer_files\env\lib\site-packages\peft\peft_model.py", line 99, in __init__
    self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
  File "I:\ob\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 154, in __init__
    self.add_adapter(adapter_name, self.peft_config[adapter_name])
  File "I:\ob\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 161, in add_adapter
    self._find_and_replace(adapter_name)
  File "I:\ob\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 246, in _find_and_replace
    raise ValueError(
ValueError: Target module QuantLinear() is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported.


-------------------------------------------------------------------------------------


Traceback (most recent call last):
  File "I:\ob\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\ob\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "I:\ob\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\ob\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\ob\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\ob\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\ob\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "I:\ob\text-generation-webui\server.py", line 76, in load_lora_wrapper
    add_lora_to_model(selected_loras)
  File "I:\ob\text-generation-webui\modules\LoRA.py", line 30, in add_lora_to_model
    shared.model.disable_adapter()
  File "I:\ob\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaForCausalLM' object has no attribute 'disable_adapter'
```

### System Info

```shell
Windows 11, 32GB ram, 5900X, Asus nvidia rtx 4090
```

**Comment by GreenTeaBD** [comment]
It needed the monkey patch, that was all.

**Comment by thusinh1969** [comment]
I run 8bits LoRA, not the 4-bits hence monkey-patch is not applied ?

**Comment by ChrisTopherTa54321** [comment]
I got around this issue by changing my model loader. When it was my models default AutoGPTQ I would hit this error and after changing to GPTQ-For-LLaMa it started working. YMMV.

**Comment by baljeetn** [comment]
Error : 
1> ValueError: Target module QuantLinear() is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported.
2> NotImplementedError: LlamaGPTQForCausalLM not support LORA peft type yet.

**Comment by DrMemoryFish** [comment]
> It needed the monkey patch, that was all.

whats the moneypatch?

**Comment by SMAntony** [comment]
> > It needed the monkey patch, that was all.
> 
> whats the moneypatch?

https://github.com/johnsmith0031/alpaca_lora_4bit/tree/main/monkeypatch

If I am not wrong, he is referring to the above link which contains the necessary monkey patch required for loading lora models with 4-bit quantization.
