### ISSUE TITLE
Build for source failure with new huggingface_hub 1.0.x package

### ISSUE THREAD

**Issue by arjunkathuria** [oobabooga/text-generation-webui#7289]
### Describe the bug

Duplicate of #7284 

### Error encountered
When building from source:-

`ImportError: cannot import name 'HfFolder' from 'huggingface_hub'`

### Error reason

Latest `huggingface_hub` package (v1.0.x)+ removed the already deprecated `HfFolder` class. This caused build fails with the above mentioned error similar to described in #7284 . 
Fix for this applied to upstream `gradio` package was to replace `HfFolder.get_token` simply with `get_token()`
see:
[1]: https://github.com/huggingface/huggingface_hub/releases/tag/v1.0.0 
[2]: https://github.com/gradio-app/gradio/commit/c38cf64df606109b8b4fa029d82fbc64fd58d850

#### Related PR
https://github.com/oobabooga/gradio/pull/1
The PR should close this.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

similar to #7284 

### Logs

```shell
`ImportError: cannot import name 'HfFolder' from 'huggingface_hub'`
```

### System Info

```shell
Linux + Nvidia
```

**Comment by arjunkathuria** [comment]
cc: @oobabooga

**Comment by oobabooga** [comment]
I have pinned the older version of huggingface-hub in the commit above; I believe this should solve the issue. huggingface-hub is not used anywhere in the project so it should be harmless.

About

https://github.com/oobabooga/gradio/pull/1#issuecomment-3476421833

the issue is that re-building the main gradio whl (not the gradio-client one) causes the svelte classes to change randomly, even though the version is the same, which in turn makes the UI look broken.

**Comment by arjunkathuria** [comment]
Sure, if that's the direction you want to go in.
Closing.
