### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'gptq_bits'

### ISSUE THREAD

**Issue by FaceDeer** [oobabooga/text-generation-webui#1163]
### Describe the bug

I installed Oobabooga on Windows 11 and downloaded the llama-13b-hf model, and a few days ago I successfully trained a lora using it. Then yesterday I ran install.bat to get the latest version of Oobabooga. It's able to successfully run the model with the lora I trained previously, but now when I try to train a new lora with the same settings that I used before I immediately got an error:

`AttributeError: 'Namespace' object has no attribute 'gptq_bits'`

In case there was something that wasn't updated correctly when I reran install.bat, I tried doing a fresh install and got the same error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install Oobabooga, download the llama-13b-hf model, load the model with "load-in-8bit" enabled, and under "training" try to do a training run with the default parameters and a raw text file dataset.

### Logs

```shell
Traceback (most recent call last):
  File "C:\oobabooga\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\oobabooga\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\oobabooga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\oobabooga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\oobabooga\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "C:\oobabooga\text-generation-webui\modules\training.py", line 127, in do_train
    if shared.args.wbits > 0 or shared.args.gptq_bits > 0:
AttributeError: 'Namespace' object has no attribute 'gptq_bits'
```
```


### System Info

```shell
Operating system: Windows 11 Pro 64-bit (10.0, Build 22621)
Processor: 13th Gen Intel Core i9-13900K (32 CPUs), ~3.0Ghz
Memory: 65535MB RAM
NVIDIA GeForce RTX 4090
Total memory: 56794 MB
VRAM: 24156 MB
Shared memory: 32638 MB
```

**Comment by Maykeye** [comment]
After running some `git bisect`, it  seems problems were introduced at commit 1566d8e34425937e6182d4425e7b85c370912d64 (Add model settings to the Models tab)

**Comment by mcmonkey4eva** [comment]
This will be fixed when #1098 - if impatient you can pull from that PR directly to use.

**Comment by FaceDeer** [comment]
I just ran install.bat to get the latest, and lora training seems to be working again. I'm doing a small training run now, if it works out I'll close this issue.

**Comment by FaceDeer** [comment]
Unfortunately, I hit [issue 1253](https://github.com/oobabooga/text-generation-webui/issues/1253) - the resulting Lora was a 1kb blank and obviously resulted in the model learning nothing. I'll close this issue anyway, though, since the specific crash I was encountering is gone and Lora training does seem to progress (I got plausible-looking updates as it went).
