### ISSUE TITLE
Can no longer start: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?

### ISSUE THREAD

**Issue by thelabcat** [oobabooga/text-generation-webui#5914]
### Describe the bug

When trying to start now, even with a fresh install, I get this:
`AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Attempt to run ./start_linux.sh

### Logs

```shell
Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Linux-x86_64.sh to /home/wilbur/text-generation-webui/installer_files/miniconda_installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 69.7M  100 69.7M    0     0  52.0M      0  0:00:01  0:00:01 --:--:-- 51.9M
PREFIX=/home/wilbur/text-generation-webui/installer_files/conda
Unpacking payload ...
                                                                                                       
Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: done
installation finished.
Miniconda version:
Traceback (most recent call last):
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
    return func(*args, **kwargs)
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/cli/main.py", line 57, in main_subshell
    p = generate_parser()
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 63, in generate_parser
    p = ArgumentParser(
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 148, in __init__
    self._subcommands = context.plugin_manager.get_hook_results("subcommands")
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/base/context.py", line 419, in plugin_manager
    from ..plugins.manager import get_plugin_manager
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/plugins/__init__.py", line 3, in <module>
    from .hookspec import hookimpl  # noqa: F401
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/plugins/hookspec.py", line 10, in <module>
    from .types import CondaSolver, CondaSubcommand, CondaVirtualPackage
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/plugins/types.py", line 6, in <module>
    from ..core.solve import Solver
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/solve.py", line 19, in <module>
    from .index import get_reduced_index, _supplement_index_with_system
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/index.py", line 15, in <module>
    from .package_cache_data import PackageCacheData
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 22, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/path_actions.py", line 28, in <module>
    from ..gateways.connection.download import download
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/gateways/connection/download.py", line 12, in <module>
    from .session import CondaSession
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/gateways/connection/session.py", line 11, in <module>
    from .adapters.s3 import S3Adapter
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/gateways/connection/adapters/s3.py", line 10, in <module>
    import boto3
  File "/home/wilbur/.local/lib/python3.10/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/wilbur/.local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import (
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/client.py", line 18, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/utils.py", line 39, in <module>
    import botocore.httpsession
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 45, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/home/wilbur/.local/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 43, in <module>
    import OpenSSL.SSL  # type: ignore[import]
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1616, in <module>
    class X509StoreFlags:
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1635, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wilbur/text-generation-webui/installer_files/conda/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/cli/main.py", line 112, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1432, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1135, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1175, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1186, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1248, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/cli/main_info.py", line 15, in <module>
    from ..core.index import _supplement_index_with_system
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/index.py", line 15, in <module>
    from .package_cache_data import PackageCacheData
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 22, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/path_actions.py", line 28, in <module>
    from ..gateways.connection.download import download
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/gateways/connection/download.py", line 12, in <module>
    from .session import CondaSession
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/gateways/connection/session.py", line 11, in <module>
    from .adapters.s3 import S3Adapter
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/gateways/connection/adapters/s3.py", line 10, in <module>
    import boto3
  File "/home/wilbur/.local/lib/python3.10/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/wilbur/.local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import (
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/client.py", line 18, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/utils.py", line 39, in <module>
    import botocore.httpsession
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 45, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/home/wilbur/.local/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 43, in <module>
    import OpenSSL.SSL  # type: ignore[import]
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1616, in <module>
    class X509StoreFlags:
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1635, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?
Traceback (most recent call last):
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
    return func(*args, **kwargs)
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/cli/main.py", line 57, in main_subshell
    p = generate_parser()
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 63, in generate_parser
    p = ArgumentParser(
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 148, in __init__
    self._subcommands = context.plugin_manager.get_hook_results("subcommands")
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/base/context.py", line 419, in plugin_manager
    from ..plugins.manager import get_plugin_manager
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/plugins/__init__.py", line 3, in <module>
    from .hookspec import hookimpl  # noqa: F401
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/plugins/hookspec.py", line 10, in <module>
    from .types import CondaSolver, CondaSubcommand, CondaVirtualPackage
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/plugins/types.py", line 6, in <module>
    from ..core.solve import Solver
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/solve.py", line 19, in <module>
    from .index import get_reduced_index, _supplement_index_with_system
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/index.py", line 15, in <module>
    from .package_cache_data import PackageCacheData
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 22, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/path_actions.py", line 28, in <module>
    from ..gateways.connection.download import download
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/gateways/connection/download.py", line 12, in <module>
    from .session import CondaSession
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/gateways/connection/session.py", line 11, in <module>
    from .adapters.s3 import S3Adapter
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/gateways/connection/adapters/s3.py", line 10, in <module>
    import boto3
  File "/home/wilbur/.local/lib/python3.10/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/wilbur/.local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import (
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/client.py", line 18, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/utils.py", line 39, in <module>
    import botocore.httpsession
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 45, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/home/wilbur/.local/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 43, in <module>
    import OpenSSL.SSL  # type: ignore[import]
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1616, in <module>
    class X509StoreFlags:
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1635, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wilbur/text-generation-webui/installer_files/conda/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/cli/main.py", line 112, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1432, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1135, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1175, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1186, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1248, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/cli/main_info.py", line 15, in <module>
    from ..core.index import _supplement_index_with_system
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/index.py", line 15, in <module>
    from .package_cache_data import PackageCacheData
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 22, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/core/path_actions.py", line 28, in <module>
    from ..gateways.connection.download import download
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/gateways/connection/download.py", line 12, in <module>
    from .session import CondaSession
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/gateways/connection/session.py", line 11, in <module>
    from .adapters.s3 import S3Adapter
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/conda/gateways/connection/adapters/s3.py", line 10, in <module>
    import boto3
  File "/home/wilbur/.local/lib/python3.10/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/wilbur/.local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import (
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/client.py", line 18, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/utils.py", line 39, in <module>
    import botocore.httpsession
  File "/home/wilbur/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 45, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/home/wilbur/.local/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 43, in <module>
    import OpenSSL.SSL  # type: ignore[import]
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1616, in <module>
    class X509StoreFlags:
  File "/home/wilbur/text-generation-webui/installer_files/conda/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1635, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?
Conda environment is empty.
```

### System Info

```shell
Fedora 39 x86-64
NVidia RTX 2060 SUPER
```

**Comment by thelabcat** [comment]
Wait a second, python 3.10? This is using my system python, 3.12. I do have an un-pathed build of 3.10 here, so is it possible the program is incorrectly using the 3.10 libraries with the system 3.12 binary?

**Comment by thelabcat** [comment]
Some of those are internal libraries though...

**Comment by thelabcat** [comment]
I'm going to try with an un-pathed python 3.11 and see if that helps, though I'm not sure why some of the libraries are showing 3.10...

**Comment by thelabcat** [comment]
Nope. Same error.

**Comment by xscode** [comment]
installing pyopenssl==24.0.0 fixed it for me

**Comment by thelabcat** [comment]
What version of Python were you using?

**Comment by xscode** [comment]
> What version of Python are you using?

3.10.12

**Comment by thelabcat** [comment]
Can confirm, using Python 3.10 and installing installing pyopenssl==24.0.0 worked. Thanks!

**Comment by thelabcat** [comment]
I'm not entirely sure how, but I did thankfully get it working with Python 3.10.14 (set by using the alias command before running start_linux.sh), and maybe the OpenSSL version you recommended?
