### ISSUE TITLE
KeyError: 'cai-chat'

### ISSUE THREAD

**Issue by jamesbraza** [oobabooga/text-generation-webui#3932]
### Describe the bug

`conda` has bitten me a lot in my travels, so I don't use `conda`.  I am trying to directly run `server.py` (`tg-webui` is this repo as a submodule):

```bash
python tg-webui/server.py
```

When doing so, I get two errors:

```
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
```

(related: https://github.com/oobabooga/text-generation-webui/issues/2397)

And

```
KeyError: 'cai-chat'
```

I would like to solve these

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`pip install` the below `requirements.txt`

<details close>
<summary>requirements.txt</summary>

```txt
#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile --no-emit-index-url
#
absl-py==1.4.0
    # via
    #   rouge-score
    #   tensorboard
accelerate==0.22.0
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
    #   peft
aiofiles==23.1.0
    # via
    #   -r requirements.in
    #   gradio
aiohttp==3.8.5
    # via
    #   datasets
    #   fsspec
    #   langchain
    #   openai
    #   text-generation
aiosignal==1.3.1
    # via aiohttp
altair==5.1.1
    # via gradio
antlr4-python3-runtime==4.9.3
    # via omegaconf
anyio==4.0.0
    # via
    #   httpcore
    #   starlette
    #   watchfiles
appdirs==1.4.4
    # via
    #   -r h2ogpt/requirements.txt
    #   wandb
appnope==0.1.3
    # via ipython
apscheduler==3.10.1
    # via -r h2ogpt/requirements.txt
arrow==1.2.3
    # via isoduration
astroid==2.15.6
    # via pylint
asttokens==2.4.0
    # via stack-data
async-timeout==4.0.3
    # via aiohttp
attrs==23.1.0
    # via
    #   aiohttp
    #   jsonlines
    #   jsonschema
    #   pytest
    #   referencing
authlib==1.2.1
    # via weaviate-client
backcall==0.2.0
    # via ipython
backoff==2.2.1
    # via posthog
beautifulsoup4==4.12.2
    # via -r h2ogpt/requirements.txt
bioc==2.0
    # via -r h2ogpt/requirements.txt
bitsandbytes==0.41.1 ; platform_system != "Windows"
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
boto3==1.26.101
    # via
    #   -r h2ogpt/requirements.txt
    #   neptune
botocore==1.29.101
    # via
    #   -r h2ogpt/requirements.txt
    #   boto3
    #   s3transfer
bravado==11.0.3
    # via neptune
bravado-core==6.1.0
    # via bravado
build==1.0.3
    # via pip-tools
cachetools==5.3.1
    # via google-auth
certifi==2023.7.22
    # via
    #   clickhouse-connect
    #   httpcore
    #   httpx
    #   requests
    #   sentry-sdk
cffi==1.15.1
    # via cryptography
cfgv==3.4.0
    # via pre-commit
chardet==5.2.0
    # via unstructured
charset-normalizer==3.2.0
    # via
    #   aiohttp
    #   pdfminer-six
    #   requests
chromadb==0.3.25
    # via -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
click==8.1.7
    # via
    #   neptune
    #   nltk
    #   pip-tools
    #   uvicorn
    #   wandb
clickhouse-connect==0.6.11
    # via chromadb
colorama==0.4.6
    # via
    #   -r requirements.in
    #   sacrebleu
coloredlogs==15.0.1
    # via
    #   onnxruntime
    #   optimum
contourpy==1.1.0
    # via matplotlib
coverage[toml]==7.3.1
    # via -r requirements.in
cramjam==2.7.0
    # via fastparquet
cryptography==41.0.3
    # via
    #   authlib
    #   pdfminer-six
ctransformers @ https://github.com/jllllll/ctransformers-cuBLAS-wheels/releases/download/AVX2/ctransformers-0.2.27+cu117-py3-none-any.whl
    # via -r requirements.in
cycler==0.11.0
    # via matplotlib
dataclasses-json==0.5.14
    # via langchain
datasets==2.13.0
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
    #   evaluate
    #   optimum
decorator==5.1.1
    # via ipython
dill==0.3.6
    # via
    #   datasets
    #   evaluate
    #   multiprocess
    #   pylint
diskcache==5.6.3
    # via llama-cpp-python
distlib==0.3.7
    # via virtualenv
docker-pycreds==0.4.0
    # via wandb
docutils==0.20.1
    # via -r h2ogpt/requirements.txt
duckdb==0.8.1
    # via chromadb
effdet==0.4.1
    # via layoutparser
einops==0.6.1
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
et-xmlfile==1.1.0
    # via openpyxl
evaluate==0.4.0
    # via -r h2ogpt/requirements.txt
execnet==2.0.2
    # via pytest-xdist
executing==1.2.0
    # via stack-data
exllamav2==0.0.1
    # via -r requirements.in
fastapi==0.95.2
    # via
    #   -r requirements.in
    #   chromadb
    #   gradio
fastparquet==2023.8.0
    # via exllamav2
ffmpy==0.3.1
    # via gradio
filelock==3.12.4
    # via
    #   -r h2ogpt/requirements.txt
    #   huggingface-hub
    #   torch
    #   transformers
    #   virtualenv
filetype==1.2.0
    # via unstructured
fire==0.5.0
    # via -r h2ogpt/requirements.txt
flatbuffers==23.5.26
    # via onnxruntime
fonttools==4.42.1
    # via matplotlib
fqdn==1.5.1
    # via jsonschema
frozenlist==1.4.0
    # via
    #   aiohttp
    #   aiosignal
fsspec[http]==2023.9.0
    # via
    #   datasets
    #   evaluate
    #   fastparquet
    #   gradio-client
    #   huggingface-hub
future==0.18.3
    # via neptune
gitdb==4.0.10
    # via gitpython
gitpython==3.1.36
    # via
    #   neptune
    #   wandb
google-auth==2.23.0
    # via
    #   google-auth-oauthlib
    #   tensorboard
google-auth-oauthlib==1.0.0
    # via tensorboard
gradio==3.41.0
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
gradio-client==0.5.0
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
    #   gradio
grpcio==1.58.0
    # via tensorboard
h11==0.14.0
    # via
    #   httpcore
    #   uvicorn
hnswlib==0.7.0
    # via chromadb
httpcore==0.18.0
    # via httpx
httptools==0.6.0
    # via uvicorn
httpx==0.25.0
    # via
    #   gradio
    #   gradio-client
huggingface-hub==0.16.4
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
    #   ctransformers
    #   datasets
    #   evaluate
    #   gradio
    #   gradio-client
    #   optimum
    #   sentence-transformers
    #   text-generation
    #   timm
    #   transformers
    #   unstructured-inference
humanfriendly==10.0
    # via coloredlogs
identify==2.5.28
    # via pre-commit
idna==3.4
    # via
    #   anyio
    #   httpx
    #   jsonschema
    #   requests
    #   yarl
importlib-resources==6.0.1
    # via gradio
iniconfig==2.0.0
    # via pytest
instructorembedding==1.0.1
    # via -r h2ogpt/requirements.txt
intervaltree==3.1.0
    # via bioc
iopath==0.1.10
    # via layoutparser
ipython==8.15.0
    # via -r requirements.in
isoduration==20.11.0
    # via jsonschema
isort==5.12.0
    # via pylint
jedi==0.19.0
    # via ipython
jinja2==3.1.2
    # via
    #   altair
    #   gradio
    #   torch
jmespath==1.0.1
    # via
    #   boto3
    #   botocore
joblib==1.3.2
    # via
    #   -r h2ogpt/requirements.txt
    #   nltk
    #   scikit-learn
jsonlines==4.0.0
    # via
    #   bioc
    #   lm-dataformat
jsonpointer==2.4
    # via jsonschema
jsonref==1.1.0
    # via bravado-core
jsonschema[format]==4.19.0
    # via
    #   altair
    #   bravado-core
    #   swagger-spec-validator
jsonschema-specifications==2023.7.1
    # via jsonschema
kiwisolver==1.4.5
    # via matplotlib
langchain==0.0.250
    # via -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
langsmith==0.0.37
    # via langchain
layoutparser[layoutmodels,tesseract]==0.3.4
    # via unstructured-inference
lazy-object-proxy==1.9.0
    # via astroid
llama-cpp-python==0.1.85 ; platform_system != "Windows"
    # via -r requirements.in
lm-dataformat==0.0.20
    # via -r h2ogpt/requirements.txt
loralib==0.1.1
    # via -r h2ogpt/requirements.txt
lxml==4.9.3
    # via
    #   bioc
    #   python-docx
    #   python-pptx
    #   sacrebleu
    #   unstructured
lz4==4.3.2
    # via clickhouse-connect
markdown==3.4.3
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
    #   tensorboard
    #   unstructured
markupsafe==2.1.3
    # via
    #   gradio
    #   jinja2
    #   werkzeug
marshmallow==3.20.1
    # via dataclasses-json
matplotlib==3.7.1
    # via
    #   -r h2ogpt/requirements.txt
    #   gradio
    #   pycocotools
matplotlib-inline==0.1.6
    # via ipython
mccabe==0.7.0
    # via pylint
monotonic==1.6
    # via
    #   bravado
    #   posthog
mpmath==1.3.0
    # via sympy
msg-parser==1.2.0
    # via unstructured
msgpack==1.0.5
    # via
    #   bravado
    #   bravado-core
multidict==6.0.4
    # via
    #   aiohttp
    #   yarl
multiprocess==0.70.14
    # via
    #   datasets
    #   evaluate
mypy==1.5.1
    # via -r requirements.in
mypy-extensions==1.0.0
    # via
    #   mypy
    #   typing-inspect
neptune==1.2.0
    # via -r h2ogpt/requirements.txt
networkx==3.1
    # via torch
ninja==1.11.1
    # via exllamav2
nltk==3.8.1
    # via
    #   -r h2ogpt/requirements.txt
    #   rouge-score
    #   sentence-transformers
    #   unstructured
nodeenv==1.8.0
    # via pre-commit
numexpr==2.8.6
    # via langchain
numpy==1.24.3
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
    #   accelerate
    #   altair
    #   chromadb
    #   contourpy
    #   datasets
    #   evaluate
    #   fastparquet
    #   gradio
    #   hnswlib
    #   langchain
    #   layoutparser
    #   llama-cpp-python
    #   matplotlib
    #   numexpr
    #   onnxruntime
    #   opencv-python
    #   optimum
    #   pandas
    #   peft
    #   pyarrow
    #   pycocotools
    #   rouge-score
    #   sacrebleu
    #   scikit-learn
    #   scipy
    #   sentence-transformers
    #   tensorboard
    #   torchvision
    #   transformers
oauthlib==3.2.2
    # via
    #   neptune
    #   requests-oauthlib
olefile==0.46
    # via msg-parser
omegaconf==2.3.0
    # via effdet
onnxruntime==1.15.1
    # via
    #   chromadb
    #   unstructured-inference
openai==0.27.8
    # via -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
openapi-schema-pydantic==1.2.4
    # via langchain
opencv-python==4.8.0.76
    # via
    #   layoutparser
    #   unstructured-inference
openpyxl==3.1.2
    # via
    #   -r h2ogpt/requirements.txt
    #   unstructured
optimum==1.13.1
    # via -r requirements.in
orjson==3.9.7
    # via gradio
overrides==7.4.0
    # via chromadb
packaging==23.1
    # via
    #   -r h2ogpt/requirements.txt
    #   accelerate
    #   altair
    #   build
    #   datasets
    #   evaluate
    #   fastparquet
    #   gradio
    #   gradio-client
    #   huggingface-hub
    #   marshmallow
    #   matplotlib
    #   neptune
    #   onnxruntime
    #   optimum
    #   peft
    #   pytesseract
    #   pytest
    #   replicate
    #   transformers
pandas==2.0.2
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
    #   altair
    #   chromadb
    #   datasets
    #   evaluate
    #   exllamav2
    #   fastparquet
    #   gradio
    #   layoutparser
    #   neptune
    #   unstructured
parso==0.8.3
    # via jedi
pathtools==0.1.2
    # via wandb
pdf2image==1.16.3
    # via
    #   layoutparser
    #   unstructured
pdfminer-six==20221105
    # via
    #   -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
    #   pdfplumber
    #   unstructured
pdfplumber==0.10.2
    # via layoutparser
peft==0.5.0
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
pexpect==4.8.0
    # via ipython
pickleshare==0.7.5
    # via ipython
pillow==9.5.0
    # via
    #   -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
    #   -r requirements.in
    #   gradio
    #   layoutparser
    #   matplotlib
    #   neptune
    #   pdf2image
    #   pdfplumber
    #   pytesseract
    #   python-pptx
    #   torchvision
    #   unstructured
pip-licenses==4.3.0
    # via -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
pip-tools==7.3.0
    # via -r requirements.in
platformdirs==3.10.0
    # via
    #   pylint
    #   virtualenv
pluggy==1.3.0
    # via pytest
portalocker==2.7.0
    # via
    #   iopath
    #   sacrebleu
posthog==3.0.1
    # via
    #   -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
    #   chromadb
pre-commit==3.4.0
    # via -r requirements.in
prettytable==3.9.0
    # via pip-licenses
prompt-toolkit==3.0.39
    # via ipython
protobuf==4.24.3
    # via
    #   onnxruntime
    #   tensorboard
    #   transformers
    #   wandb
psutil==5.9.5
    # via
    #   -r h2ogpt/requirements.txt
    #   accelerate
    #   neptune
    #   peft
    #   wandb
ptyprocess==0.7.0
    # via pexpect
pure-eval==0.2.2
    # via stack-data
py-cpuinfo==9.0.0
    # via ctransformers
pyarrow==13.0.0
    # via datasets
pyasn1==0.5.0
    # via
    #   pyasn1-modules
    #   rsa
pyasn1-modules==0.3.0
    # via google-auth
pycocotools==2.0.7
    # via effdet
pycparser==2.21
    # via cffi
pydantic==1.10.12
    # via
    #   -r requirements.in
    #   chromadb
    #   fastapi
    #   gradio
    #   langchain
    #   langsmith
    #   openapi-schema-pydantic
    #   replicate
    #   text-generation
pydub==0.25.1
    # via gradio
pyenchant==3.2.2
    # via pylint
pygments==2.16.1
    # via ipython
pyjwt==2.8.0
    # via neptune
pylint[spelling]==2.17.5
    # via -r requirements.in
pynvml==11.5.0
    # via -r h2ogpt/requirements.txt
pypandoc==1.11 ; sys_platform == "darwin" and platform_machine == "arm64"
    # via
    #   -r h2ogpt/requirements.txt
    #   unstructured
pyparsing==3.1.1
    # via matplotlib
pypdf==3.14.0
    # via -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
pypdfium2==4.19.0
    # via
    #   -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
    #   pdfplumber
pyphen==0.14.0
    # via textstat
pyproject-hooks==1.0.0
    # via build
pytesseract==0.3.10
    # via layoutparser
pytest==7.2.2
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
    #   pytest-xdist
pytest-xdist==3.2.1
    # via -r h2ogpt/requirements.txt
python-dateutil==2.8.2
    # via
    #   arrow
    #   botocore
    #   bravado
    #   bravado-core
    #   matplotlib
    #   pandas
    #   posthog
python-docx==0.8.11
    # via unstructured
python-dotenv==1.0.0
    # via
    #   -r h2ogpt/requirements.txt
    #   uvicorn
python-magic==0.4.27
    # via unstructured
python-multipart==0.0.6
    # via
    #   gradio
    #   unstructured-inference
python-pptx==0.6.22
    # via unstructured
pytz==2023.3.post1
    # via
    #   apscheduler
    #   bravado-core
    #   clickhouse-connect
    #   pandas
pyyaml==6.0.1
    # via
    #   -r requirements.in
    #   accelerate
    #   bravado
    #   bravado-core
    #   datasets
    #   gradio
    #   huggingface-hub
    #   langchain
    #   layoutparser
    #   omegaconf
    #   peft
    #   pre-commit
    #   swagger-spec-validator
    #   timm
    #   transformers
    #   uvicorn
    #   wandb
referencing==0.30.2
    # via
    #   jsonschema
    #   jsonschema-specifications
regex==2023.8.8
    # via
    #   nltk
    #   sacrebleu
    #   tiktoken
    #   transformers
replicate==0.10.0
    # via -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
requests==2.31.0
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
    #   bravado
    #   bravado-core
    #   chromadb
    #   datasets
    #   evaluate
    #   fsspec
    #   gradio
    #   gradio-client
    #   huggingface-hub
    #   langchain
    #   langsmith
    #   neptune
    #   openai
    #   posthog
    #   replicate
    #   requests-file
    #   requests-oauthlib
    #   responses
    #   tensorboard
    #   tiktoken
    #   torchvision
    #   transformers
    #   unstructured
    #   wandb
    #   weaviate-client
requests-file==1.5.1
    # via -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
requests-oauthlib==1.3.1
    # via
    #   google-auth-oauthlib
    #   neptune
responses==0.18.0
    # via evaluate
rfc3339-validator==0.1.4
    # via jsonschema
rfc3987==1.3.8
    # via jsonschema
rouge-score==0.1.2
    # via -r h2ogpt/requirements.txt
rpds-py==0.10.3
    # via
    #   jsonschema
    #   referencing
rsa==4.9
    # via google-auth
s3transfer==0.6.2
    # via boto3
sacrebleu==2.3.1
    # via -r h2ogpt/requirements.txt
safetensors==0.3.2
    # via
    #   -r requirements.in
    #   exllamav2
    #   peft
    #   timm
    #   transformers
scikit-learn==1.2.2
    # via
    #   -r h2ogpt/requirements.txt
    #   sentence-transformers
scipy==1.11.2
    # via
    #   -r requirements.in
    #   layoutparser
    #   scikit-learn
    #   sentence-transformers
semantic-version==2.10.0
    # via gradio
sentence-transformers==2.2.2
    # via -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
sentencepiece==0.1.99
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
    #   exllamav2
    #   sentence-transformers
    #   transformers
sentry-sdk==1.31.0
    # via wandb
setproctitle==1.3.2
    # via wandb
simplejson==3.19.1
    # via
    #   bravado
    #   bravado-core
six==1.16.0
    # via
    #   apscheduler
    #   asttokens
    #   bravado
    #   bravado-core
    #   docker-pycreds
    #   fire
    #   neptune
    #   posthog
    #   python-dateutil
    #   requests-file
    #   rfc3339-validator
    #   rouge-score
smmap==5.0.0
    # via gitdb
sniffio==1.3.0
    # via
    #   anyio
    #   httpcore
    #   httpx
sortedcontainers==2.4.0
    # via intervaltree
soupsieve==2.5
    # via beautifulsoup4
sqlalchemy==2.0.20
    # via langchain
stack-data==0.6.2
    # via ipython
starlette==0.27.0
    # via fastapi
swagger-spec-validator==3.0.3
    # via
    #   bravado-core
    #   neptune
sympy==1.12
    # via
    #   onnxruntime
    #   optimum
    #   torch
tabulate==0.9.0
    # via
    #   -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
    #   -r h2ogpt/requirements.txt
    #   sacrebleu
    #   unstructured
tenacity==8.2.3
    # via langchain
tensorboard==2.13.0
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
tensorboard-data-server==0.7.1
    # via tensorboard
termcolor==2.3.0
    # via fire
text-generation==0.6.0
    # via -r h2ogpt/requirements.txt
textstat==0.7.3
    # via -r h2ogpt/requirements.txt
threadpoolctl==3.2.0
    # via scikit-learn
tiktoken==0.4.0
    # via -r h2ogpt/requirements.txt
timm==0.9.7
    # via effdet
tokenizers==0.13.3
    # via
    #   -r h2ogpt/requirements.txt
    #   chromadb
    #   transformers
tomlkit==0.12.1
    # via pylint
toolz==0.12.0
    # via altair
torch==2.0.1
    # via
    #   -r requirements.in
    #   accelerate
    #   effdet
    #   exllamav2
    #   layoutparser
    #   optimum
    #   peft
    #   sentence-transformers
    #   timm
    #   torchaudio
    #   torchvision
torchaudio==2.0.2
    # via -r requirements.in
torchvision==0.15.2
    # via
    #   -r requirements.in
    #   effdet
    #   layoutparser
    #   sentence-transformers
    #   timm
tqdm==4.66.1
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
    #   bioc
    #   chromadb
    #   datasets
    #   evaluate
    #   huggingface-hub
    #   iopath
    #   nltk
    #   openai
    #   peft
    #   sentence-transformers
    #   transformers
    #   weaviate-client
traitlets==5.10.0
    # via
    #   ipython
    #   matplotlib-inline
transformers[sentencepiece]==4.33.1
    # via
    #   -r h2ogpt/requirements.txt
    #   -r requirements.in
    #   optimum
    #   peft
    #   sentence-transformers
    #   unstructured-inference
typing-extensions==4.7.1
    # via
    #   bravado
    #   chromadb
    #   gradio
    #   gradio-client
    #   huggingface-hub
    #   iopath
    #   llama-cpp-python
    #   mypy
    #   pydantic
    #   sqlalchemy
    #   swagger-spec-validator
    #   torch
    #   typing-inspect
typing-inspect==0.9.0
    # via dataclasses-json
tzdata==2023.3
    # via pandas
tzlocal==5.0.1
    # via apscheduler
ujson==5.8.0
    # via lm-dataformat
unstructured[local-inference]==0.9.0
    # via -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
unstructured-inference==0.5.7
    # via unstructured
uri-template==1.3.0
    # via jsonschema
urllib3==1.26.16
    # via
    #   -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
    #   -r h2ogpt/requirements.txt
    #   botocore
    #   clickhouse-connect
    #   google-auth
    #   neptune
    #   requests
    #   responses
    #   sentry-sdk
uvicorn[standard]==0.23.2
    # via
    #   chromadb
    #   gradio
uvloop==0.17.0
    # via uvicorn
validators==0.21.0
    # via weaviate-client
virtualenv==20.24.5
    # via pre-commit
wandb==0.15.10
    # via -r requirements.in
watchfiles==0.20.0
    # via uvicorn
wcwidth==0.2.6
    # via
    #   prettytable
    #   prompt-toolkit
weaviate-client==3.22.1
    # via -r h2ogpt/reqs_optional/requirements_optional_langchain.txt
webcolors==1.13
    # via jsonschema
websocket-client==1.6.3
    # via neptune
websockets==11.0.3
    # via
    #   gradio
    #   gradio-client
    #   uvicorn
werkzeug==2.3.7
    # via tensorboard
wheel==0.41.2
    # via
    #   pip-tools
    #   tensorboard
wrapt==1.15.0
    # via astroid
xlrd==2.0.1
    # via unstructured
xlsxwriter==3.1.3
    # via python-pptx
xxhash==3.3.0
    # via
    #   datasets
    #   evaluate
yarl==1.9.2
    # via aiohttp
zstandard==0.21.0
    # via
    #   clickhouse-connect
    #   lm-dataformat

# The following packages are considered to be unsafe in a requirements file:
# pip
# setuptools
```

</details>

I also placed [TheBloke/Llama-2-13B-chat-GGUF/llama-2-13b-chat.Q4_K_S.gguf](https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/tree/main) in the appropriate `models` folder

### Logs

```shell
/Users/user/code/project/venv/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Traceback (most recent call last):
  File "/Users/user/code/project/tg-webui/server.py", line 226, in <module>
    create_interface()
  File "/Users/user/code/project/tg-webui/server.py", line 109, in create_interface
    ui_chat.create_ui()
  File "/Users/user/code/project/tg-webui/modules/ui_chat.py", line 26, in create_ui
    shared.gradio['display'] = gr.HTML(value=chat_html_wrapper({'internal': [], 'visible': []}, shared.settings['name1'], shared.settings['name2'], 'chat', 'cai-chat'))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/project/tg-webui/modules/html_generator.py", line 300, in chat_html_wrapper
    return generate_cai_chat_html(history['visible'], name1, name2, style, reset_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/project/tg-webui/modules/html_generator.py", line 217, in generate_cai_chat_html
    output = f'<style>{chat_styles[style]}</style><div class="chat" id="chat"><div class="messages">'
                       ~~~~~~~~~~~^^^^^^^
KeyError: 'cai-chat'
```

### System Info

```shell
macOS Ventura 13.5.2
M1 chip
```

**Comment by jamesbraza** [comment]
Okay, the resolution is: relative imports 🥲 

The issue doesn't persist if I `cd` to the `text-generation-webui` submodule:

```bash
cd tg-webui
python server.py
```

The desirable resolution is fixing this relative import so it doesn't matter how one invokes `server.py`

Alternately, feel free to close this out as user error.

**Comment by hkordbacheh** [comment]
I'm also having a problem:

KeyError: 'cai-chat'

apparently, the problem is related to the def create_ui function in the ui_chat.py file, in line 27:

shared.gradio['display'] = gr.HTML(value=chat_html_wrapper({'internal': [], 'visible': []}, '', '', 'chat', 'cai-chat', ''))

I'm using pyenv and  poetry environmnet, my pyproject.toml file is as below:

[tool.poetry.dependencies]
python = "3.11.7"
accelerate = "==0.25.*"
bitsandbytes = "0.41.1"
llama-cpp-python = "^0.2.27"
autoawq = "0.1.8"
rich = "^13.7.0"
gradio = "==3.50.*"
markdown = "^3.5.1"
exllamav2 = "0.0.11"
colorama = "^0.4.6"
datasets = "^2.16.1"
einops = "^0.7.0"
hqq = "0.1.1.post1"
lm-eval = "0.3.0"
numpy = "==1.24.*"
optimum = "==1.16.*"
pandas = "^2.1.4"
peft = "==0.7.*"
pillow = "^10.2.0"
pyyaml = "^6.0.1"
requests = "^2.31.0"
safetensors = "0.4.1"
scipy = "^1.11.4"
sentencepiece = "^0.1.99"
tensorboard = "^2.15.1"
transformers = "==4.36.*"
tqdm = "^4.66.1"
wandb = "^0.16.1"

after some search, i suspected to the version, somebodey was saying that apparently, Cai chat is deprecated and i should use --chat now, i replaced the ' 'cai-chat' in the above mentioned line with '--chat', but still it didn't work.

my folder structure is like below:

-textgen
------text-generation-webui
------poetry.lock
------pyproject.toml

this is how i run the code, inside the textgen folder i run the below command:

poetry shell
python text-generation-webui/server.py

and this is the error I'm getting:

/home/m/coding/sandbox/textgen/text-generation-webui/server.py:254 in <module>                                                                                                                                          
│   253         # Launch the web UI                                                                                                                                                                                           
│ ❱ 254         create_interface()                                                                                                                                                                                            
│   255         while True:                                                                                                                                                                                                   │
│ /home/hkord/coding/sandbox/textgen/text-generation-webui/server.py:128 in create_interface                                                                                                                                  │
│   127         # Text Generation tab                                                                                                                                                                                         ││ ❱ 128         ui_chat.create_ui()                                                                                                                                                                                           ││   129         ui_default.create_ui()                                                                                                                                                                                        │
│ /home/hkord/coding/sandbox/textgen/text-generation-webui/modules/ui_chat.py:27 in create_ui                                                                                                                                 │
│    26             with gr.Column(elem_id='chat-col'):                                                                                                                                                                       ││ ❱  27                 shared.gradio['display'] = gr.HTML(value=chat_html_wrapper({'internal':                                                                                                                               ││    28                 # shared.gradio['display'] = gr.HTML(value=chat_html_wrapper({'internal'                                                                                                                              │
│ /home/hkord/coding/sandbox/textgen/text-generation-webui/modules/html_generator.py:308 in chat_html_wrapper                                                                                                                 │
│   307     else:                                                                                                                                                                                                             ││ ❱ 308         return generate_cai_chat_html(history['visible'], name1, name2, style, character                                                                                                                              ││   309                                                                                                                                                                                                                       │
│ /home/hkord/coding/sandbox/textgen/text-generation-webui/modules/html_generator.py:225 in generate_cai_chat_html                                                                                                            ││   224 def generate_cai_chat_html(history, name1, name2, style, character, reset_cache=False):                                                                                                                               ││ ❱ 225     output = f'<style>{chat_styles[style]}</style><div class="chat" id="chat"><div class                                                                                                                              ││   226                                                                                                                                                                                                                       │─────────────────────────────────────────────────────────────────╯
KeyError: 'cai-chat'

can anybody help me to resolve it please?
